fhe:
  scheme: ckks
  scale_mod_size: 50
  enable_bootstrapping: false
  clientContextFile: "client_context_file.bin"
  serverContextFile: "server_context_file.bin"
  secretKeyFile: "secret_key_file.bin"
  publicKeyFile: "public_key_file.bin"
  rotKeysFile: "rot_keys.bin"
  mulKeysFile: "mul_keys.bin"
  keyLocation: "keys/"

matvec:
  depth: 1
  ringDims: [ 32768, 65536]
  matrixSizes: [ 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  max_matrix_value: 5.0
  max_vector_value: 3.0
  rotation_indices: [1]
  outputCSV: "bench/matvec/matvec_ring_bench.csv"
  functionVariants:
    - Halevi
#    - parallel

polyeval:
  ringDims: [ 32768, 65536 ]
  depth: 5
  vectorSizes: [ 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
  max_vector_value: 3.0
  outputCSV: "bench/polyeval/polyeval_ring_bench.csv"
  functionVariants:
    - openfhe
    - custom
  chebyshevCoeff:
    - -0.0000000000
    - 0.9548601071
    - 0.0000000000
    - -0.2283708821
    - -0.0000000000
    - 0.0422605239
    - 0.0000000000
    - -0.0048556560
    - -0.0000000000
    - 0.0003380545
    - 0.0000000000
    - -0.0000138422
    - -0.0000000000
    - 0.0000003060
    - 0.0000000000
    - -0.0000000028
